# Generated by Django 3.2.4 on 2021-07-06 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serving_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.DeleteModel(
            name='Photo',
        ),
    ]
